# Generated by Django 3.2 on 2024-01-07 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, max_length=700)),
                ('image', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('ourvision', models.TextField(blank=True, max_length=500)),
                ('ourmission', models.TextField(blank=True, max_length=500)),
                ('expertteam', models.TextField(blank=True, max_length=500)),
                ('teammember1', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('teammember2', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('teammember3', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('communityengagement', models.TextField(blank=True, max_length=500)),
                ('communityimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('qualityandsafety', models.TextField(blank=True, max_length=500)),
                ('yourtrusted', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Aboutpagee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, max_length=700)),
                ('image', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('ourvision', models.TextField(blank=True, max_length=500)),
                ('ourmission', models.TextField(blank=True, max_length=500)),
                ('expertteam', models.TextField(blank=True, max_length=500)),
                ('teammember1', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('teammember2', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('teammember3', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('communityengagement', models.TextField(blank=True, max_length=500)),
                ('communityimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('qualityandsafety', models.TextField(blank=True, max_length=500)),
                ('yourtrusted', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('content', models.TextField(blank=True, default='', max_length=800)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/%Y/%m/%d')),
                ('title1', models.CharField(default='', max_length=500)),
                ('content1', models.TextField(blank=True, default='', max_length=700)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='homepage/%Y/%m/%d')),
                ('title2', models.CharField(default='', max_length=500)),
                ('content2', models.TextField(blank=True, default='', max_length=700)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='homepage/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/%Y/%m/%d')),
                ('imagedescription', models.CharField(blank=True, max_length=500)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='homepage/%Y/%m/%d')),
                ('imagedescription1', models.CharField(blank=True, max_length=500)),
                ('post1', models.CharField(blank=True, max_length=500)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='homepage/%Y/%m/%d')),
                ('imagedescription2', models.CharField(blank=True, max_length=500)),
                ('post2', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=55)),
                ('text', models.TextField(max_length=100000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=55)),
                ('text', models.TextField(max_length=7000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('content', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
